//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop.Servico {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AtivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ativo {
            get {
                return this.AtivoField;
            }
            set {
                if ((this.AtivoField.Equals(value) != true)) {
                    this.AtivoField = value;
                    this.RaisePropertyChanged("Ativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Unidade", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Unidade : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InativoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Inativo {
            get {
                return this.InativoField;
            }
            set {
                if ((this.InativoField.Equals(value) != true)) {
                    this.InativoField = value;
                    this.RaisePropertyChanged("Inativo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataAlteracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataInclusaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadeCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadeEstoqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadeVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioAlteracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioInclusaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataAlteracao {
            get {
                return this.DataAlteracaoField;
            }
            set {
                if ((this.DataAlteracaoField.Equals(value) != true)) {
                    this.DataAlteracaoField = value;
                    this.RaisePropertyChanged("DataAlteracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataInclusao {
            get {
                return this.DataInclusaoField;
            }
            set {
                if ((this.DataInclusaoField.Equals(value) != true)) {
                    this.DataInclusaoField = value;
                    this.RaisePropertyChanged("DataInclusao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Inativo {
            get {
                return this.InativoField;
            }
            set {
                if ((this.InativoField.Equals(value) != true)) {
                    this.InativoField = value;
                    this.RaisePropertyChanged("Inativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadeCompra {
            get {
                return this.UnidadeCompraField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadeCompraField, value) != true)) {
                    this.UnidadeCompraField = value;
                    this.RaisePropertyChanged("UnidadeCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadeEstoque {
            get {
                return this.UnidadeEstoqueField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadeEstoqueField, value) != true)) {
                    this.UnidadeEstoqueField = value;
                    this.RaisePropertyChanged("UnidadeEstoque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadeVenda {
            get {
                return this.UnidadeVendaField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadeVendaField, value) != true)) {
                    this.UnidadeVendaField = value;
                    this.RaisePropertyChanged("UnidadeVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioAlteracao {
            get {
                return this.UsuarioAlteracaoField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioAlteracaoField, value) != true)) {
                    this.UsuarioAlteracaoField = value;
                    this.RaisePropertyChanged("UsuarioAlteracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioInclusao {
            get {
                return this.UsuarioInclusaoField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioInclusaoField, value) != true)) {
                    this.UsuarioInclusaoField = value;
                    this.RaisePropertyChanged("UsuarioInclusao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocalEstoque", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class LocalEstoque : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InativoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Inativo {
            get {
                return this.InativoField;
            }
            set {
                if ((this.InativoField.Equals(value) != true)) {
                    this.InativoField = value;
                    this.RaisePropertyChanged("Inativo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servico.IServico")]
    public interface IServico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/ObterUsuarioPorCodigo", ReplyAction="http://tempuri.org/IServico/ObterUsuarioPorCodigoResponse")]
        Desktop.Servico.Usuario ObterUsuarioPorCodigo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/Autenticar", ReplyAction="http://tempuri.org/IServico/AutenticarResponse")]
        Desktop.Servico.Usuario Autenticar(string codigo, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/AlterarSenha", ReplyAction="http://tempuri.org/IServico/AlterarSenhaResponse")]
        void AlterarSenha(ref Desktop.Servico.Usuario usuario, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/InserirUsuario", ReplyAction="http://tempuri.org/IServico/InserirUsuarioResponse")]
        void InserirUsuario(ref Desktop.Servico.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/AlterarUsuario", ReplyAction="http://tempuri.org/IServico/AlterarUsuarioResponse")]
        void AlterarUsuario(ref Desktop.Servico.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/DeletarUsuario", ReplyAction="http://tempuri.org/IServico/DeletarUsuarioResponse")]
        void DeletarUsuario(Desktop.Servico.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/ObterUnidadePorCodigo", ReplyAction="http://tempuri.org/IServico/ObterUnidadePorCodigoResponse")]
        Desktop.Servico.Unidade ObterUnidadePorCodigo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/ObterListaUnidades", ReplyAction="http://tempuri.org/IServico/ObterListaUnidadesResponse")]
        Desktop.Servico.Unidade[] ObterListaUnidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/InserirUnidade", ReplyAction="http://tempuri.org/IServico/InserirUnidadeResponse")]
        void InserirUnidade(ref Desktop.Servico.Unidade usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/AlterarUnidade", ReplyAction="http://tempuri.org/IServico/AlterarUnidadeResponse")]
        void AlterarUnidade(ref Desktop.Servico.Unidade usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/ObterProdutoPorCodigo", ReplyAction="http://tempuri.org/IServico/ObterProdutoPorCodigoResponse")]
        Desktop.Servico.Produto ObterProdutoPorCodigo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/InserirProduto", ReplyAction="http://tempuri.org/IServico/InserirProdutoResponse")]
        void InserirProduto(ref Desktop.Servico.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/AlterarProduto", ReplyAction="http://tempuri.org/IServico/AlterarProdutoResponse")]
        void AlterarProduto(ref Desktop.Servico.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/ObterLocalEstoquePorCodigo", ReplyAction="http://tempuri.org/IServico/ObterLocalEstoquePorCodigoResponse")]
        Desktop.Servico.LocalEstoque ObterLocalEstoquePorCodigo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/InserirLocalEstoque", ReplyAction="http://tempuri.org/IServico/InserirLocalEstoqueResponse")]
        void InserirLocalEstoque(ref Desktop.Servico.LocalEstoque local);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/AlterarLocalEstoque", ReplyAction="http://tempuri.org/IServico/AlterarLocalEstoqueResponse")]
        void AlterarLocalEstoque(ref Desktop.Servico.LocalEstoque local);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoChannel : Desktop.Servico.IServico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoClient : System.ServiceModel.ClientBase<Desktop.Servico.IServico>, Desktop.Servico.IServico {
        
        public ServicoClient() {
        }
        
        public ServicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Desktop.Servico.Usuario ObterUsuarioPorCodigo(string codigo) {
            return base.Channel.ObterUsuarioPorCodigo(codigo);
        }
        
        public Desktop.Servico.Usuario Autenticar(string codigo, string senha) {
            return base.Channel.Autenticar(codigo, senha);
        }
        
        public void AlterarSenha(ref Desktop.Servico.Usuario usuario, string senha) {
            base.Channel.AlterarSenha(ref usuario, senha);
        }
        
        public void InserirUsuario(ref Desktop.Servico.Usuario usuario) {
            base.Channel.InserirUsuario(ref usuario);
        }
        
        public void AlterarUsuario(ref Desktop.Servico.Usuario usuario) {
            base.Channel.AlterarUsuario(ref usuario);
        }
        
        public void DeletarUsuario(Desktop.Servico.Usuario usuario) {
            base.Channel.DeletarUsuario(usuario);
        }
        
        public Desktop.Servico.Unidade ObterUnidadePorCodigo(string codigo) {
            return base.Channel.ObterUnidadePorCodigo(codigo);
        }
        
        public Desktop.Servico.Unidade[] ObterListaUnidades() {
            return base.Channel.ObterListaUnidades();
        }
        
        public void InserirUnidade(ref Desktop.Servico.Unidade usuario) {
            base.Channel.InserirUnidade(ref usuario);
        }
        
        public void AlterarUnidade(ref Desktop.Servico.Unidade usuario) {
            base.Channel.AlterarUnidade(ref usuario);
        }
        
        public Desktop.Servico.Produto ObterProdutoPorCodigo(string codigo) {
            return base.Channel.ObterProdutoPorCodigo(codigo);
        }
        
        public void InserirProduto(ref Desktop.Servico.Produto produto) {
            base.Channel.InserirProduto(ref produto);
        }
        
        public void AlterarProduto(ref Desktop.Servico.Produto produto) {
            base.Channel.AlterarProduto(ref produto);
        }
        
        public Desktop.Servico.LocalEstoque ObterLocalEstoquePorCodigo(string codigo) {
            return base.Channel.ObterLocalEstoquePorCodigo(codigo);
        }
        
        public void InserirLocalEstoque(ref Desktop.Servico.LocalEstoque local) {
            base.Channel.InserirLocalEstoque(ref local);
        }
        
        public void AlterarLocalEstoque(ref Desktop.Servico.LocalEstoque local) {
            base.Channel.AlterarLocalEstoque(ref local);
        }
    }
}
