//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop.Servico {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servico.IServico")]
    public interface IServico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/ObterUsuarioPorCodigo", ReplyAction="http://tempuri.org/IServico/ObterUsuarioPorCodigoResponse")]
        Entidades.Usuario ObterUsuarioPorCodigo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/Autenticar", ReplyAction="http://tempuri.org/IServico/AutenticarResponse")]
        Entidades.Usuario Autenticar(string codigo, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/AlterarSenha", ReplyAction="http://tempuri.org/IServico/AlterarSenhaResponse")]
        void AlterarSenha(ref Entidades.Usuario usuario, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/InserirUsuario", ReplyAction="http://tempuri.org/IServico/InserirUsuarioResponse")]
        void InserirUsuario(ref Entidades.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/AlterarUsuario", ReplyAction="http://tempuri.org/IServico/AlterarUsuarioResponse")]
        void AlterarUsuario(ref Entidades.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/DeletarUsuario", ReplyAction="http://tempuri.org/IServico/DeletarUsuarioResponse")]
        void DeletarUsuario(Entidades.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/ObterUnidadePorCodigo", ReplyAction="http://tempuri.org/IServico/ObterUnidadePorCodigoResponse")]
        Entidades.Unidade ObterUnidadePorCodigo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/ObterListaUnidades", ReplyAction="http://tempuri.org/IServico/ObterListaUnidadesResponse")]
        Entidades.Unidade[] ObterListaUnidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/InserirUnidade", ReplyAction="http://tempuri.org/IServico/InserirUnidadeResponse")]
        void InserirUnidade(ref Entidades.Unidade usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/AlterarUnidade", ReplyAction="http://tempuri.org/IServico/AlterarUnidadeResponse")]
        void AlterarUnidade(ref Entidades.Unidade usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/ObterProdutoPorCodigo", ReplyAction="http://tempuri.org/IServico/ObterProdutoPorCodigoResponse")]
        Entidades.Produto ObterProdutoPorCodigo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/InserirProduto", ReplyAction="http://tempuri.org/IServico/InserirProdutoResponse")]
        void InserirProduto(ref Entidades.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/AlterarProduto", ReplyAction="http://tempuri.org/IServico/AlterarProdutoResponse")]
        void AlterarProduto(ref Entidades.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/ObterLocalEstoquePorCodigo", ReplyAction="http://tempuri.org/IServico/ObterLocalEstoquePorCodigoResponse")]
        Entidades.LocalEstoque ObterLocalEstoquePorCodigo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/InserirLocalEstoque", ReplyAction="http://tempuri.org/IServico/InserirLocalEstoqueResponse")]
        void InserirLocalEstoque(ref Entidades.LocalEstoque local);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/AlterarLocalEstoque", ReplyAction="http://tempuri.org/IServico/AlterarLocalEstoqueResponse")]
        void AlterarLocalEstoque(ref Entidades.LocalEstoque local);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IServicoChannel : Desktop.Servico.IServico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServicoClient : System.ServiceModel.ClientBase<Desktop.Servico.IServico>, Desktop.Servico.IServico {
        
        public ServicoClient() {
        }
        
        public ServicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entidades.Usuario ObterUsuarioPorCodigo(string codigo) {
            return base.Channel.ObterUsuarioPorCodigo(codigo);
        }
        
        public Entidades.Usuario Autenticar(string codigo, string senha) {
            return base.Channel.Autenticar(codigo, senha);
        }
        
        public void AlterarSenha(ref Entidades.Usuario usuario, string senha) {
            base.Channel.AlterarSenha(ref usuario, senha);
        }
        
        public void InserirUsuario(ref Entidades.Usuario usuario) {
            base.Channel.InserirUsuario(ref usuario);
        }
        
        public void AlterarUsuario(ref Entidades.Usuario usuario) {
            base.Channel.AlterarUsuario(ref usuario);
        }
        
        public void DeletarUsuario(Entidades.Usuario usuario) {
            base.Channel.DeletarUsuario(usuario);
        }
        
        public Entidades.Unidade ObterUnidadePorCodigo(string codigo) {
            return base.Channel.ObterUnidadePorCodigo(codigo);
        }
        
        public Entidades.Unidade[] ObterListaUnidades() {
            return base.Channel.ObterListaUnidades();
        }
        
        public void InserirUnidade(ref Entidades.Unidade usuario) {
            base.Channel.InserirUnidade(ref usuario);
        }
        
        public void AlterarUnidade(ref Entidades.Unidade usuario) {
            base.Channel.AlterarUnidade(ref usuario);
        }
        
        public Entidades.Produto ObterProdutoPorCodigo(string codigo) {
            return base.Channel.ObterProdutoPorCodigo(codigo);
        }
        
        public void InserirProduto(ref Entidades.Produto produto) {
            base.Channel.InserirProduto(ref produto);
        }
        
        public void AlterarProduto(ref Entidades.Produto produto) {
            base.Channel.AlterarProduto(ref produto);
        }
        
        public Entidades.LocalEstoque ObterLocalEstoquePorCodigo(string codigo) {
            return base.Channel.ObterLocalEstoquePorCodigo(codigo);
        }
        
        public void InserirLocalEstoque(ref Entidades.LocalEstoque local) {
            base.Channel.InserirLocalEstoque(ref local);
        }
        
        public void AlterarLocalEstoque(ref Entidades.LocalEstoque local) {
            base.Channel.AlterarLocalEstoque(ref local);
        }
    }
}
